### ISSUE TITLE
Building placement grid alignment

### ISSUE THREAD

**Issue by perfecthumaninterface** [TiredOfCoding/ProjectBurst#21]
Placement of buildings (that are larger than 1x1) should be grid aligned. a 2x2 building should fill 4 grid spaces with the edges aligned with the grid lines.

**Comment by TiredOfCoding** [comment]
Would we have non-square sized buildings, e.g. 2x3?

**Comment by perfecthumaninterface** [comment]
I think we should assume yes, although it's not decided yet.

**Comment by TiredOfCoding** [comment]
Okay, will keep possible building rotation using mouse wheel in background.

**Comment by TiredOfCoding** [comment]
Updated building in the following release.
https://github.com/TiredOfCoding/ProjectBurst/releases/tag/v0.1.0-alpha2

**Comment by perfecthumaninterface** [comment]
The "shield" building appears to be 2x2 but behaves like it's 1x1.

I think the shield should be 1x1 and the turret should be 2x2.

The 1x3 wall is exactly what I was imagining. It feels surprisingly good to place it using the rotation. I don't think I want to emphasize wall building too much in the game but for now this is good.

**Comment by perfecthumaninterface** [comment]
I think there should be a check to whether or not a building is set as "rotateable." Being able to rotate some buildings may be unnecessary but it would still rotate the building sprite which we might not want.

**Comment by TiredOfCoding** [comment]
Addressed:
https://github.com/TiredOfCoding/ProjectBurst/releases/tag/v0.1.0-alpha3

**Comment by perfecthumaninterface** [comment]
Building alignment should be addressed again after adjusting the grid transform.

**Comment by TiredOfCoding** [comment]
Readdressed:
https://github.com/TiredOfCoding/ProjectBurst/releases/tag/v0.1.0-alpha4
