### ISSUE TITLE
Printscrn does not work in game

### ISSUE THREAD

**Issue by perfecthumaninterface** [TiredOfCoding/ProjectBurst#22]
Printscrn doesn't currently capture the game screen correctly.

It's necessary to capture screenshots of gameplay for discussing bugs and design elements.

I don't know if there is a "fix" but perhaps using "borderless" fullscreen mode will allow this to work better.

If so, it might be good to have a button that can toggle between borderless and "true" fullscreen. In this case maybe borderless should be the default.

**Comment by TiredOfCoding** [comment]
Addressed:
https://github.com/TiredOfCoding/ProjectBurst/releases/tag/v0.1.0-alpha3
