### ISSUE TITLE
Increase safe area radius by 0.5

### ISSUE THREAD

**Issue by perfecthumaninterface** [TiredOfCoding/ProjectBurst#23]
We'll probably want to set the size of this in whole grid lengths but since it's measured from the center of a grid square we should add 0.5 to it so the circle reaches the edge of grid squares in cardinal directions.

The current check for placing buildings within the safe zone seems to be fine so this should *not* be changed.

Ultimately we will probably want to set the size of safe zones with one value though so both elements should be dependent on the same value, just add the 0.5 to the circle drawn.

**Comment by TiredOfCoding** [comment]
Adressed:
https://github.com/TiredOfCoding/ProjectBurst/releases/tag/v0.1.0-alpha3
