### ISSUE TITLE
Player movement jitter

### ISSUE THREAD

**Issue by perfecthumaninterface** [TiredOfCoding/ProjectBurst#26]
Currently the player movement appears jittery while the rest of the game is smooth.

When interpolation is enabled on the player object's rigidbody2d, the player movement appears smooth for some reason while the rest of the game appears jittery while moving.

**Comment by TiredOfCoding** [comment]
Addressed:
https://github.com/TiredOfCoding/ProjectBurst/releases/tag/v0.1.0-alpha4
