### ISSUE TITLE
Player visuals/sprite

### ISSUE THREAD

**Issue by perfecthumaninterface** [TiredOfCoding/ProjectBurst#4]
Player sprite should be a simple triangle shape that faces the reticle at all times. The hitbox for the player should be small and drawn on top of the sprite in high contrast.

The exact size of the player sprite and hitbox may need to be adjusted in the future.

The player may need multiple collision boxes, i.e. a larger collision for interacting with walls.

![image](https://user-images.githubusercontent.com/35180513/53668872-2d2e5f80-3c43-11e9-98da-8e5c713141da.png)

**Comment by TiredOfCoding** [comment]
Updated Player sprite:
https://github.com/TiredOfCoding/ProjectBurst/releases/tag/v0.1.0-alpha2
