### ISSUE TITLE
Cursor/reticle design

### ISSUE THREAD

**Issue by perfecthumaninterface** [TiredOfCoding/ProjectBurst#6]
A reticle to replace the default mouse cursor. 

The reticle should be a simple png file that could be edited in Photoshop if necessary. 

While in building mode, the reticle should be hidden and the default cursor shown again (placeholder behavior).

**Comment by TiredOfCoding** [comment]
Updated cursor:
https://github.com/TiredOfCoding/ProjectBurst/releases/tag/v0.1.0-alpha2
